version: '3.8'

services:
  calculatrice:
    build: 
      context: ./calculatriceSpringBoot/calculatrice
      dockerfile: Dockerfile
    container_name: calculatrice
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calculatrice.rule=Host(`calculatrice.apercheron.fr`)"
      - "traefik.http.routers.calculatrice.entrypoints=websecure"
      - "traefik.http.routers.calculatrice.tls.certresolver=letsencrypt"
      - "traefik.http.services.calculatrice.loadbalancer.server.port=8080"
    depends_on:
      - traefik

networks:
  traefik-network:
    external: true
